### PR TITLE
Added bower config file and UMD boilerplate

### PR DESCRIPTION
**Pull request by hiddentao**
Added bower config file. **Note:** Need to [`bower register`](http://bower.io/docs/creating-packages/) once merged into master so that it's available in the bower repo.

Added UMD boilerplate for use in browsers.

### CODE REVIEW

**Comment by ben-ng** [comment]
Cool thanks! I published this to npm but got a 403 error trying to register the package on bower.

If you know how to do this, just go ahead and register it on my behalf -- I don't use bower.

Mind if I ask what you are using this module for? (:

**Comment by hiddentao** [comment]
Thanks. I found this through your `linalg` module - I like that too. I plan on building some machine learning algorithms for use in the browser. None of the other modules out there focus on performance and accuracy enough to my liking.

**Comment by hiddentao** [comment]
I'm working on the bower registration - mvaldetaro/twbs-buttons#2

**Comment by ben-ng** [comment]
Nice! We have the same goals then. I started these modules because I was anticipating implementing some machine learning algorithms for work and noticed that existing stuff wasn't accurate enough or didn't support stuff like arbitrary vector lengths.

There's still work to be done -- my project got delayed by a few months at work, but I'm continuing to work on these modules as a hobby. I'm adding you as a contributor so you can keep things going without me.

**Comment by hiddentao** [comment]
Thanks :)

**Pull request merged**
